# Generated by Django 4.2.30 on 2026-09-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_shifttype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開始時刻'),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開始時刻'),
        ),
    ]
