# Generated by Django 4.2.30 on 2026-09-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_shift_end_time_alter_shift_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttype',
            name='color',
            field=models.CharField(blank=True, choices=[('#FADADD', '淡色1'), ('#FFE4CC', '淡色2'), ('#FFF3B0', '淡色3'), ('#D9F2D0', '淡色4'), ('#CDEFE6', '淡色5'), ('#D7EEF8', '淡色6'), ('#DDE7FF', '淡色7'), ('#E8DDF7', '淡色8'), ('#F6DDF0', '淡色9'), ('#F6E5D5', '淡色10'), ('#E2F0CB', '淡色11'), ('#C9F0DD', '淡色12'), ('#CFE8E8', '淡色13'), ('#D2E3FC', '淡色14'), ('#E4D7FF', '淡色15'), ('#FFD6E7', '淡色16'), ('#FBE7C6', '淡色17'), ('#E9F5DB', '淡色18'), ('#D8F3DC', '淡色19'), ('#BDE0FE', '淡色20'), ('#CDB4DB', '淡色21'), ('#FFC8DD', '淡色22'), ('#FFDDD2', '淡色23'), ('#FDFFB6', '淡色24'), ('#CAFFBF', '淡色25'), ('#BDB2FF', '淡色26')], max_length=7, null=True, unique=True, verbose_name='色'),
        ),
    ]
