# Generated by Django 4.2.30 on 2026-09-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_shifttype_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='タスク名')),
                ('due_date', models.DateField(verbose_name='期限')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('memo', models.CharField(blank=True, max_length=160, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク',
                'ordering': ['is_completed', 'due_date', 'title'],
            },
        ),
    ]
