# Generated by Django 4.2.30 on 2026-09-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_shifttype_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
