# Generated by Django 4.2.30 on 2026-09-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttype',
            name='break_minutes',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, '30分'), (45, '45分'), (60, '60分')], null=True, verbose_name='休憩'),
        ),
    ]
