# Generated by Django 4.2.30 on 2026-09-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_shifttype_break_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='actual_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='実働終了時刻'),
        ),
        migrations.AddField(
            model_name='shift',
            name='actual_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='実働開始時刻'),
        ),
    ]
