# Generated by Django 4.2.30 on 2026-09-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_shift_actual_end_time_shift_actual_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': [models.OrderBy(models.F('management_number'), nulls_last=True), 'name'], 'verbose_name': 'スタッフ', 'verbose_name_plural': 'スタッフ'},
        ),
        migrations.AddField(
            model_name='staff',
            name='management_number',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='管理番号'),
        ),
    ]
