# Generated by Django 4.2.30 on 2026-09-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_staff_options_staff_management_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='hourly_wage',
            field=models.PositiveIntegerField(default=0, verbose_name='時給'),
        ),
    ]
