# Generated by Django 4.2.30 on 2026-09-22 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_staff_hourly_wage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='項目名')),
                ('amount_type', models.CharField(choices=[('fixed', '固定'), ('variable', '変動')], default='fixed', max_length=10, verbose_name='金額区分')),
                ('fixed_amount', models.PositiveIntegerField(default=0, verbose_name='固定金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '差引項目',
                'verbose_name_plural': '差引項目',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffSalaryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='金額')),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_amounts', to='notes.salarydeduction', verbose_name='差引項目')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_deductions', to='notes.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': 'スタッフ別差引額',
                'verbose_name_plural': 'スタッフ別差引額',
                'ordering': ['deduction__name', 'staff__management_number', 'staff__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='staffsalarydeduction',
            constraint=models.UniqueConstraint(fields=('staff', 'deduction'), name='unique_staff_salary_deduction'),
        ),
    ]
