# Generated by Django 4.2.30 on 2026-09-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_salarydeduction_staffsalarydeduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydeduction',
            name='direction',
            field=models.CharField(choices=[('subtract', '−'), ('add', '+')], default='subtract', max_length=10, verbose_name='加減区分'),
        ),
    ]
