# Generated by Django 4.2.30 on 2026-09-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_salarydeduction_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalarydeduction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='適用'),
        ),
    ]
