# Generated by Django 4.2.30 on 2026-09-23 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_staffsalarydeduction_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttype',
            name='name',
        ),
    ]
