# Generated by Django 4.2.30 on 2026-09-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_remove_shifttype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='actual_day_off',
            field=models.BooleanField(default=False, verbose_name='実働休み'),
        ),
    ]
