# Generated by Django 4.2.30 on 2026-09-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0018_shift_actual_day_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='holiday_hourly_wage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='土日祝日時給'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='hourly_wage',
            field=models.PositiveIntegerField(default=0, verbose_name='平日時給'),
        ),
    ]
