# Generated by Django 4.2.30 on 2026-09-23 02:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0019_staff_holiday_hourly_wage_alter_staff_hourly_wage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPaidLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='対象月')),
                ('days', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='有給日数')),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='1日あたりの時間')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_paid_leave', to='notes.staff')),
            ],
        ),
        migrations.AddConstraint(
            model_name='monthlypaidleave',
            constraint=models.UniqueConstraint(fields=('staff', 'month'), name='unique_staff_paid_leave_month'),
        ),
    ]
