# Generated by Django 4.2.30 on 2026-09-23 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0020_monthlypaidleave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffWageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_month', models.DateField(verbose_name='適用開始月')),
                ('hourly_wage', models.PositiveIntegerField(verbose_name='平日時給')),
                ('holiday_hourly_wage', models.PositiveIntegerField(blank=True, null=True, verbose_name='土日祝日時給')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage_history', to='notes.staff')),
            ],
            options={
                'ordering': ['-effective_month'],
            },
        ),
        migrations.AddConstraint(
            model_name='staffwagehistory',
            constraint=models.UniqueConstraint(fields=('staff', 'effective_month'), name='unique_staff_wage_month'),
        ),
    ]
