# Generated by Django 4.2.30 on 2026-09-23 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0021_staffwagehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='paid_leave_hours_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='有給1日あたりの時間'),
        ),
    ]
