# Generated by Django 4.2.30 on 2026-09-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0022_staff_paid_leave_hours_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='actual_break_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='実働休憩（分）'),
        ),
    ]
