# Generated by Django 4.2.30 on 2026-09-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0023_shift_actual_break_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttype',
            name='code',
            field=models.CharField(choices=[('休', '休'), ('希望休', '希望休'), ('指定休', '指定休'), ('その他', 'その他'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=8, unique=True, verbose_name='区分'),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='color',
            field=models.CharField(blank=True, choices=[('#FADADD', '赤系1'), ('#FFDDD2', '赤系2'), ('#FFE4CC', '橙系1'), ('#FBE7C6', '橙系2'), ('#F6E5D5', '橙系3'), ('#FFF3B0', '黄系1'), ('#FDFFB6', '黄系2'), ('#E9F5DB', '黄緑系1'), ('#E2F0CB', '黄緑系2'), ('#D9F2D0', '緑系1'), ('#D8F3DC', '緑系2'), ('#CAFFBF', '緑系3'), ('#C9F0DD', '青緑系1'), ('#CDEFE6', '青緑系2'), ('#CFE8E8', '水色系1'), ('#D7EEF8', '水色系2'), ('#BDE0FE', '水色系3'), ('#D2E3FC', '青系1'), ('#DDE7FF', '青系2'), ('#BDB2FF', '紫系1'), ('#CDB4DB', '紫系2'), ('#E4D7FF', '紫系3'), ('#E8DDF7', '紫系4'), ('#F6DDF0', '桃系1'), ('#FFD6E7', '桃系2'), ('#FFC8DD', '桃系3'), ('#DC2626', '赤'), ('#222222', '黒'), ('#808080', 'グレー'), ('#F97316', 'オレンジ')], max_length=7, null=True, unique=True, verbose_name='色'),
        ),
    ]
