# Generated by Django 4.2.30 on 2026-09-25 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0025_default_leave_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='actual_shift_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_shifts', to='notes.shifttype', verbose_name='実働区分'),
        ),
    ]
