# Generated by Django 4.2.30 on 2026-09-25 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0027_alter_shifttype_break_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStaffSalaryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='対象月')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='金額')),
                ('is_active', models.BooleanField(default=True, verbose_name='適用')),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_staff_amounts', to='notes.salarydeduction')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_salary_deductions', to='notes.staff')),
            ],
        ),
        migrations.AddConstraint(
            model_name='monthlystaffsalarydeduction',
            constraint=models.UniqueConstraint(fields=('staff', 'deduction', 'month'), name='unique_staff_deduction_month'),
        ),
    ]
