# Generated by Django 4.2.30 on 2026-09-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0028_monthlystaffsalarydeduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='show_in_salary',
            field=models.BooleanField(default=True, verbose_name='給料一覧に表示'),
        ),
    ]
