# Generated by Django 4.2.30 on 2026-09-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0029_staff_show_in_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalarydeduction',
            name='reset_from_month',
            field=models.DateField(blank=True, null=True, verbose_name='リセット開始月'),
        ),
    ]
